name: Test

# Trigger workflow on push and pull requests to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Set default working directory for all run steps
    defaults:
      run:
        working-directory: src/web
    
    # Define Node.js version matrix
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      # Checkout repository code
      # actions/checkout@v3
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Setup Node.js environment with caching
      # actions/setup-node@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: src/web/package-lock.json
      
      # Install dependencies securely using clean install
      - name: Install dependencies
        run: npm ci
        env:
          CI: true
          NODE_ENV: test
      
      # Run tests with coverage reporting
      - name: Run tests
        run: npm test -- --coverage --watchAll=false --ci
        env:
          CI: true
          NODE_ENV: test
          FORCE_COLOR: true